# Site Settings
title: PDFP 2028 Study Site
description: A study site for PDFP2028.
url: "https://pdfp2028.github.io"
baseurl: ""

# Build Settings
theme: minima
plugins:

# Custom Global Variables
author_name: Paul Lewis
